### ISSUE TITLE
(edit: it works!)  Isn't working with other .bin files other than testfile.bin 

### ISSUE THREAD

**Issue by bobtechcorp** [ClaesClaes/Arduino-ESP32-BLE-OTA-iOS-SwiftUI#3]
Any suggestions?

**Comment by ClaesClaes** [comment]
@bobtechcorp Glad you made it work. For others with the same problem. The iOS example has the name hardcoded in line 38 of ContenView.swift. See link below
 
[https://github.com/ClaesClaes/Arduino-ESP32-BLE-OTA-iOS-SwiftUI/blob/08371643d6f0f60ad3ad37d3f56600417ae38ad2/iOS_OTA_ESP32/iOS_OTA_ESP32/ContentView.swift#L38]
